/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC4
 */
public class formPDAM extends javax.swing.JFrame {

    /**
     * Creates new form formPDAM
     */
    public formPDAM() {
        initComponents();
        
    }
    private javax.swing.JTextField txttarif(){
        return txttarif;
    }
    private javax.swing.JTextField txtnama(){
      return txtnama;
    }
    private javax.swing.JTextField txtmeterbulanini(){
        return txtmeterbulanini;
    }
    private javax.swing.JTextField txtkodepelanggan(){
        return txtkodepelanggan;
    }
    private javax.swing.JTextField txtdiskon(){
        return txtdiskon;
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkodepelanggan = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtmeterbulanini = new javax.swing.JTextField();
        meterbulanlalu = new javax.swing.JTextField();
        txttarif = new javax.swing.JTextField();
        txtdiskon = new javax.swing.JTextField();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("kode pelanggan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 16);

        jLabel2.setText("nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 90, 16);

        jLabel3.setText("meter bulan ini");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 90, 16);

        jLabel4.setText("meter bulan lalu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 90, 16);

        jLabel5.setText("tarif");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 90, 16);

        jLabel6.setText("diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 160, 90, 16);

        txtkodepelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodepelangganActionPerformed(evt);
            }
        });
        getContentPane().add(txtkodepelanggan);
        txtkodepelanggan.setBounds(130, 10, 230, 22);
        getContentPane().add(txtnama);
        txtnama.setBounds(130, 40, 230, 22);

        txtmeterbulanini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmeterbulaniniActionPerformed(evt);
            }
        });
        getContentPane().add(txtmeterbulanini);
        txtmeterbulanini.setBounds(130, 70, 230, 22);

        meterbulanlalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterbulanlaluActionPerformed(evt);
            }
        });
        getContentPane().add(meterbulanlalu);
        meterbulanlalu.setBounds(130, 100, 230, 22);

        txttarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarifActionPerformed(evt);
            }
        });
        getContentPane().add(txttarif);
        txttarif.setBounds(130, 130, 230, 22);
        getContentPane().add(txtdiskon);
        txtdiskon.setBounds(130, 160, 230, 20);

        btninsert.setText("insert");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        getContentPane().add(btninsert);
        btninsert.setBounds(10, 190, 75, 23);

        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(120, 190, 72, 23);

        btndelete.setText("delete");
        getContentPane().add(btndelete);
        btndelete.setBounds(220, 190, 72, 23);

        btncancel.setText("cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(320, 190, 72, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "kdplgn", "nama", "mbi", "mbl", "tarif", "diskon", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 452, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodepelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodepelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodepelangganActionPerformed

    private void txtmeterbulaniniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmeterbulaniniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmeterbulaniniActionPerformed

    private void meterbulanlaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterbulanlaluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meterbulanlaluActionPerformed

    private void txttarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarifActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btninsertActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPDAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPDAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPDAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPDAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPDAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField meterbulanlalu;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txtkodepelanggan;
    private javax.swing.JTextField txtmeterbulanini;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttarif;
    // End of variables declaration//GEN-END:variables
}
